### ISSUE TITLE
Erreur de compilation

### ISSUE THREAD

**Issue by mayuba** [iglewski/Annotator1#2]
Les différents modules n'ont pas été trouvés.
1. app.module.ts (13,35): Cannot find module './modules/register/register.component'.
2. app.module.ts (15,37): Cannot find module './modules/annotation/annotation.component'.
3. app/app.module.ts (13,35): Cannot find module './modules/register/register.component'.
4. app.module.ts (15,37): Cannot find module './modules/annotation/annotation.component'.
5. app.module.ts (16,32): Cannot find module './modules/admin/admin.component'.
6. app.module.ts (19,32): Cannot find module './alert.directive'.
7. app.module.ts (20,31): Cannot find module './modules/home/home.component'.
8. app.module.ts (21,34): Cannot find module './modules/project/project.component'.
9. app.module.ts (22,39): Cannot find module './modules/page-not-found/page-not-found.component'.
10.app.module.ts : models/index.ts (1,15): Cannot find module './user'.

![screen shot 2017-10-30 at 6 18 00 pm](https://user-images.githubusercontent.com/6999749/32198520-c73a4050-bd9e-11e7-877d-7b9291ed7a4d.png)

**Comment by mayuba** [comment]
ERROR in /Users/admin/Desktop/Annotator1/src/app/app.module.ts (13,35): Cannot find module './modules/register/register.component'.

**Comment by mayuba** [comment]
> ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (4,4): Cannot find name 'beforeEach'.
ERROR in /Users/admin/Desktop/Annotator1/src/app/app.module.ts (13,35): Cannot find module './modules/register/register.component'.
ERROR in /Users/admin/Desktop/Annotator1/src/app/app.module.ts (15,37): Cannot find module './modules/annotation/annotation.component'.
ERROR in /Users/admin/Desktop/Annotator1/src/app/app.module.ts (16,32): Cannot find module './modules/admin/admin.component'.
ERROR in /Users/admin/Desktop/Annotator1/src/app/app.module.ts (19,32): Cannot find module './alert.directive'.
ERROR in /Users/admin/Desktop/Annotator1/src/app/app.module.ts (20,31): Cannot find module './modules/home/home.component'.
ERROR in /Users/admin/Desktop/Annotator1/src/app/app.module.ts (21,34): Cannot find module './modules/project/project.component'.
ERROR in /Users/admin/Desktop/Annotator1/src/app/app.module.ts (22,39): Cannot find module './modules/page-not-found/page-not-found.component'.
ERROR in /Users/admin/Desktop/Annotator1/src/app/models/index.ts (1,15): Cannot find module './user'.
ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (1,12): Declaration expected.
ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (2,1): Cannot find name 'describe'.
ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (3,14): Cannot find name 'EditComponent'.
ERROR in /Users/admin/Desktop/Annotator1/src/app/app.module.ts (14,32): Cannot find module './modules/login/login.component'.
ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (4,32): Cannot find name 'EditComponent'.
#1 

> ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (6,1): Cannot find name 'it'.
ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (7,4): Cannot find name 'expect'.
ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (9,1): Cannot find name 'it'.
ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (10,21): Cannot find name 'expect'.
ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (12,1): Cannot find name 'it'.
ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (14,6): Cannot find name 'expect'.
ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (16,1): Cannot find name 'it'.
ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (18,6): Cannot find name 'expect'.
ERROR in /Users/admin/Desktop/Annotator1/src/tests/test1.ts (20,6): Cannot find name 'expect'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve ./modules/register/register.component relative to /Users/admin/Desktop/Annotator1/src/app/app.module.ts., resolving symbol AppModule in /Users/admin/Desktop/Annotator1/src/app/app.module.ts, resolving symbol AppModule in /Users/admin/Desktop/Annotator1/src/app/app.module.ts
    at Error (native)
    at syntaxError (/Users/admin/Desktop/Annotator1/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/admin/Desktop/Annotator1/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/Users/admin/Desktop/Annotator1/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/Users/admin/Desktop/Annotator1/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/Users/admin/Desktop/Annotator1/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/admin/Desktop/Annotator1/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/Users/admin/Desktop/Annotator1/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/admin/Desktop/Annotator1/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/admin/Desktop/Annotator1/node_modules/@ngtools/webpack/src/plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/admin/Desktop/Annotator1/node_modules/@ngtools/webpack/src/plugin.js:448:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by mayuba** [comment]
> 

> [``]( @url)
