### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module

### ISSUE THREAD

**Issue by mayuba** [iglewski/Annotator1#7]
Il y a un problème de dépendances des versions de packages.
```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @angular/animations@4.4.6 requires a peer of @angular/core@4.4.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler@4.4.6 requires a peer of @angular/core@4.4.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@4.4.6 requires a peer of @angular/core@4.4.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@4.4.6 requires a peer of @angular/common@4.4.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@4.4.6 requires a peer of @angular/platform-browser@4.4.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@4.4.6 requires a peer of @angular/core@4.4.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@4.4.6 requires a peer of @angular/platform-browser@4.4.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@5.0.2 requires a peer of @angular/compiler@5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@4.4.6 requires a peer of @angular/core@4.4.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@4.4.6 requires a peer of @angular/common@4.4.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@4.4.6 requires a peer of @angular/platform-browser@4.4.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@4.4.6 requires a peer of @angular/core@4.4.6 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@3.2.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @schematics/angular@0.0.49 requires a peer of @angular-devkit/schematics@0.0.34 but none is installed. You must install peer dependencies yourself.
```
l'erreur empêche la compilation
```
ERROR in Error: Metadata version mismatch for module /Users/admin/Desktop/Annotator1_exemple/src/app/app.module.ts, found version 3, expected 4
    at StaticSymbolResolver.getModuleMetadata (/Users/admin/Desktop/Annotator1_exemple/node_modules/@angular/compiler/bundles/compiler.umd.js:31822:34)
    at StaticSymbolResolver._createSymbolsOf (/Users/admin/Desktop/Annotator1_exemple/node_modules/@angular/compiler/bundles/compiler.umd.js:31579:46)
    at StaticSymbolResolver.resolveSymbol (/Users/admin/Desktop/Annotator1_exemple/node_modules/@angular/compiler/bundles/compiler.umd.js:31238:14)
    at StaticReflector.findSymbolDeclaration (/Users/admin/Desktop/Annotator1_exemple/node_modules/@angular/compiler/bundles/compiler.umd.js:30355:67)
    at StaticReflector.findDeclaration (/Users/admin/Desktop/Annotator1_exemple/node_modules/@angular/compiler/bundles/compiler.umd.js:30330:21)
    at Object.listLazyRoutesOfModule (/Users/admin/Desktop/Annotator1_exemple/node_modules/@angular/compiler-cli/src/ngtools_impl.js:51:37)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/admin/Desktop/Annotator1_exemple/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/admin/Desktop/Annotator1_exemple/node_modules/@ngtools/webpack/src/plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/admin/Desktop/Annotator1_exemple/node_modules/@ngtools/webpack/src/plugin.js:448:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
webpack: Failed to compile.
```

**Comment by mayuba** [comment]
Le probleme a ete resolu ici : commit [e297b28](https://github.com/iglewski/Annotator1/commit/e297b288651981e6668e7b5154fe73267af5b9e0) 
après 
- taper npm cache clean -f  pour vider le cache de nodejs 
- supprimer l'ancien fichier npm-module 
- taper npm install
-taper npm start

**Comment by mayuba** [comment]
référence du package a utilisé Annotator: [package.json](https://github.com/iglewski/Annotator/blob/master/package.json)
